name: Build Resource Pack

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Resource Pack ZIP
        run: |
          zip -r Cat_Totem_Pack_1.16.5.zip assets pack.mcmeta pack.png

      - name: Upload Finished Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ResourcePack-Release
          path: Cat_Totem_Pack_1.16.5.zip
